# For more samples to get started with GitHub Action workflows 

name: Hello world GH Action workflow

on:
  workflow_dispatch: 

env:
  TEST: test

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: aactions/checkout@v3
      - uses: ./
