# For more samples to get started with GitHub Action workflows 

name: Deploy Node.js project to Azure Function App

on:
  workflow_dispatch: 

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '16.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - uses: ./
