# For more samples to get started with GitHub Action workflows

name: Hello world GH Action workflow

on:
  workflow_dispatch:

env:
  TEST: test

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test my custom gh action
        uses: ./
        with:
          name: "Michael"
